version: "3"
# Create a standin database for local development for testing
volumes:
  cumulus_postgres_data: {}

services:
  cumulusdb:
    image: mdillon/postgis
    volumes:
      - cumulus_postgres_data:/var/lib/postgresql/data
      - ./database_files:/database_files
    environment:
        - POSTGRES_PASSWORD=postgres
    ports:
        - "5432:5432"
  elasticmq:
    image: softwaremill/elasticmq
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
    ports:
      - "9324:9324"
  listener:
    build:
      context: ../async_listener
    environment:
      - AWS_ACCESS_KEY_ID=x
      - AWS_SECRET_ACCESS_KEY=x
      - AWS_REGION=us-east-1
      - CUMULUS_DBUSER=postgres
      - CUMULUS_DBPASS=postgres
      - CUMULUS_DBNAME=postgres
      - CUMULUS_DBHOST=cumulusdb
      - CUMULUS_DBSSLMODE=disable
      - CUMULUS_ASYNC_ENGINE_PACKAGER=AWSSQS
      - CUMULUS_ASYNC_ENGINE_PACKAGER_TARGET=local/http://elasticmq:9324/queue/cumulus-packager
      - CUMULUS_ASYNC_ENGINE_STATISTICS=AWSSQS
      - CUMULUS_ASYNC_ENGINE_STATISTICS_TARGET=local/http://elasticmq:9324/queue/cumulus-statistics
      - CUMULUS_MIN_RECONN=10s
      - CUMULUS_MAX_RECONN=1m
  packager:
    build:
      context: ../async_packager
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID_SQS=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY_SQS=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION_SQS=elasticmq
      - CUMULUS_MOCK_S3_UPLOAD=TRUE
      - QUEUE_NAME_PACKAGER=cumulus-packager
      - QUEUE_NAME_PACKAGER_UPDATE=cumulus-packager-update
      - CUMULUS_DBUSER=postgres
      - CUMULUS_DBPASS=postgres
      - CUMULUS_DBNAME=postgres
      - CUMULUS_DBHOST=cumulusdb
      - CUMULUS_DBSSLMODE=disable
      - ENDPOINT_URL=http://elasticmq:9324
      - PACKAGER_UPDATE_INTERVAL=5
    # Volume to persist packager created file
    volumes:
      - ./packager_files:/output
  statistics:
    build:
      context: ../async_statistics
    environment:
      - AWS_REGION=$AWS_REGION
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - CUMULUS_MOCK_S3_UPLOAD=TRUE
      - QUEUE_NAME_STATISTICS=cumulus-statistics
      - CUMULUS_DBUSER=postgres
      - CUMULUS_DBPASS=postgres
      - CUMULUS_DBNAME=postgres
      - CUMULUS_DBHOST=cumulusdb
      - CUMULUS_DBSSLMODE=disable
      - ENDPOINT_URL=http://elasticmq:9324
    # Volume to persist packager created file
    volumes:
      - ./packager_files:/output
    restart: always
  nginx:
    image: nginx
    ports: 
        - "80:80"
    build: 
      context: ../async_packager
      dockerfile: Dockerfile-nginx
    volumes:
      - ./packager_files:/usr/share/nginx/html/cumulus/download/dss
