version: "3"
# Create a standin database for local development for testing
volumes:
  cumulus_postgres_data: {}

services:
  cumulusdb:
    image: mdillon/postgis
    volumes:
      - cumulus_postgres_data:/var/lib/postgresql/data
    environment:
        - POSTGRES_PASSWORD=postgres
    ports:
        - "5432:5432"
  packager:
    image: cumulus/packager
    environment:
      - CUMULUS_DBUSER=postgres
      - CUMULUS_DBPASS=postgres
      - CUMULUS_DBNAME=postgres
      - CUMULUS_DBHOST=localhost
      - CUMULUS_DBSSLMODE=disable
