name: Build API Lambda

on:
  push:
    branches: [develop]
    paths:
      - 'api/**'

jobs:

  GoAPI:
    name: Build API
    runs-on: ubuntu-latest
    steps:
      - name: Echo Workflow Disabled
        run: echo "CI Workflow Disabled"
      # - name: Set up Go 1.13
      #   uses: actions/setup-go@v1
      #   with:
      #     go-version: 1.13
      #   id: go

      # - name: Check out code into the Go module directory
      #   uses: actions/checkout@v2

      # - name: Build and Package for Lambda
      #   run: cd api && make package

      # - name: Deploy to Development
      #   env:
      #     AWS_DEFAULT_REGION: ${{ secrets.RSGISCI_AWS_DEFAULT_REGION }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.RSGISCI_AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.RSGISCI_AWS_SECRET_ACCESS_KEY }}
      #   run: cd api && make deploy
